// +build !ignore_autogenerated

/*
 * Copyright (c) 2019 WSO2 Inc. (http:www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http:www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfigs) DeepCopyInto(out *DeploymentConfigs) {
	*out = *in
	in.MessagingSystem.DeepCopyInto(&out.MessagingSystem)
	in.PersistenceVolume.DeepCopyInto(&out.PersistenceVolume)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfigs.
func (in *DeploymentConfigs) DeepCopy() *DeploymentConfigs {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnviromentVariable) DeepCopyInto(out *EnviromentVariable) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnviromentVariable.
func (in *EnviromentVariable) DeepCopy() *EnviromentVariable {
	if in == nil {
		return nil
	}
	out := new(EnviromentVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingSystem) DeepCopyInto(out *MessagingSystem) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingSystem.
func (in *MessagingSystem) DeepCopy() *MessagingSystem {
	if in == nil {
		return nil
	}
	out := new(MessagingSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessagingSystemConfig) DeepCopyInto(out *MessagingSystemConfig) {
	*out = *in
	if in.BootstrapServers != nil {
		in, out := &in.BootstrapServers, &out.BootstrapServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessagingSystemConfig.
func (in *MessagingSystemConfig) DeepCopy() *MessagingSystemConfig {
	if in == nil {
		return nil
	}
	out := new(MessagingSystemConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCRequest) DeepCopyInto(out *PVCRequest) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCRequest.
func (in *PVCRequest) DeepCopy() *PVCRequest {
	if in == nil {
		return nil
	}
	out := new(PVCRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCResource) DeepCopyInto(out *PVCResource) {
	*out = *in
	out.Requests = in.Requests
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCResource.
func (in *PVCResource) DeepCopy() *PVCResource {
	if in == nil {
		return nil
	}
	out := new(PVCResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceVolume) DeepCopyInto(out *PersistenceVolume) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Resources = in.Resources
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceVolume.
func (in *PersistenceVolume) DeepCopy() *PersistenceVolume {
	if in == nil {
		return nil
	}
	out := new(PersistenceVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pod) DeepCopyInto(out *Pod) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pod.
func (in *Pod) DeepCopy() *Pod {
	if in == nil {
		return nil
	}
	out := new(Pod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiddhiProcess) DeepCopyInto(out *SiddhiProcess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiddhiProcess.
func (in *SiddhiProcess) DeepCopy() *SiddhiProcess {
	if in == nil {
		return nil
	}
	out := new(SiddhiProcess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiddhiProcess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiddhiProcessList) DeepCopyInto(out *SiddhiProcessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SiddhiProcess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiddhiProcessList.
func (in *SiddhiProcessList) DeepCopy() *SiddhiProcessList {
	if in == nil {
		return nil
	}
	out := new(SiddhiProcessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiddhiProcessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiddhiProcessSpec) DeepCopyInto(out *SiddhiProcessSpec) {
	*out = *in
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnviromentVariables != nil {
		in, out := &in.EnviromentVariables, &out.EnviromentVariables
		*out = make([]EnviromentVariable, len(*in))
		copy(*out, *in)
	}
	out.SiddhiIngressTLS = in.SiddhiIngressTLS
	out.SiddhiPod = in.SiddhiPod
	in.DeploymentConfigs.DeepCopyInto(&out.DeploymentConfigs)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiddhiProcessSpec.
func (in *SiddhiProcessSpec) DeepCopy() *SiddhiProcessSpec {
	if in == nil {
		return nil
	}
	out := new(SiddhiProcessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiddhiProcessStatus) DeepCopyInto(out *SiddhiProcessStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiddhiProcessStatus.
func (in *SiddhiProcessStatus) DeepCopy() *SiddhiProcessStatus {
	if in == nil {
		return nil
	}
	out := new(SiddhiProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}
